# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-09 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170707_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('front', '前端'), ('database', '数据库'), ('back', '后端')], default='back', max_length=10, verbose_name='课程类别'),
        ),
    ]
