# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': '视频资源', 'verbose_name_plural': '视频资源'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='课程地址'),
        ),
    ]
