# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170710_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learns',
            field=models.CharField(default='', max_length=200, verbose_name='你能学到什么'),
        ),
        migrations.AddField(
            model_name='course',
            name='prompt',
            field=models.CharField(default='', max_length=200, verbose_name='课程须知'),
        ),
    ]
