# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170709_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='addr',
            field=models.CharField(default='', max_length=50, verbose_name='地址'),
        ),
    ]
